export const questions = [
  "¿Quién no se bañó hoy?",
  "¿Quién es el más mentiroso del grupo?",
  "¿Quién tiene el humor más negro?",
  "¿Quién es el más dramático?",
  "¿Quién se cree más gracioso de lo que es?",
  "¿Quién es el más chismoso?",
  "¿Quién tiene el celular más roto?",
  "¿Quién es más probable que termine en la cárcel?",
  "¿Quién es el más tacaño?",
  "¿Quién es más probable que se case primero?",
  "¿Quién es más probable que se haga rico?",
  "¿Quién tiene el peor gusto musical?",
  "¿Quién es más probable que olvide tu cumpleaños?",
  "¿Quién es el más despistado?",
  "¿Quién ronca más fuerte?",
  "¿Quién es más probable que llegue tarde a su propia boda?",
  "¿Quién es el peor cocinero?",
  "¿Quién es más probable que sobreviva a un apocalipsis zombie?",
  "¿Quién tiene el peor sentido de la moda?",
  "¿Quién es el más dramatic@ cuando está enfermo?",
]
