export const questions = [
  // --- PRIMERA PERSONA (El protagonista es el narrador) ---
  "Me acaban de asesinar. ¿Quién fue?",
  "Desperté en una bañera llena de hielo sin un riñón. ¿Quién me lo sacó?",
  "Alguien me vendió a una secta. ¿Quién fue?",
  "Estoy tirado en la calle a las 5am llorando. ¿Quién me dejó ahí?",
  "Me acabo de enterar que mi pareja me engaña. ¿Con quién de ustedes?",
  "Necesito que alguien me saque de la cárcel a las 4am. ¿Quién NO vendría?",
  "Me están por operar del corazón. ¿A quién NO dejaría a cargo?",
  "Estoy en coma. ¿Quién desenchufa la máquina para cargar el celular?",
  "Me voy de viaje y necesito que alguien cuide a mi mascota. ¿Quién la mata?",
  "Gané la lotería. ¿Quién aparece de la nada diciendo que somos mejores amigos?",
  "Me caso. ¿A quién NO invito al casamiento?",
  "Abrí un bar. ¿Quién lo funde en un mes?",
  "Tengo un secreto que no le conté a nadie. ¿Quién ya lo sabe?",
  "Me emborraché y mandé un mensaje que no debía. ¿A quién de ustedes se lo mandé?",
  "Estoy a punto de saltar en paracaídas. ¿Quién me empuja antes de tiempo?",
  "La policía encontró drogas en la guantera de mi auto. ¿Quién las puso ahí?",
  "Me desperté con un tatuaje horrible en la cara. ¿Quién me convenció de hacérmelo?",
  "Estoy colgando de un precipicio y necesito una mano. ¿Quién me pisa los dedos?",
  "Me mordió un zombie. ¿Quién me pega un tiro en la cabeza sin dudarlo ni un segundo?",
  "Me hackearon el celular y filtraron mis fotos desnudo/a. ¿Quién fue el primero en guardarlas?",
  "Perdí todos mis ahorros en una estafa piramidal. ¿Quién de ustedes me metió?",
  "Estoy en un interrogatorio policial. ¿Quién se quiebra a los 5 minutos y me delata?",
  "Tengo que borrar mi historial de internet antes de morir. ¿A quién le doy la contraseña?",
  "Organicé una fiesta sorpresa. ¿Quién es el idiota que se le escapa y me la arruina?",
  "Me voy a vivir a otro país. ¿Quién se queda con mi casa y cambia la cerradura al día siguiente?",
  "Tengo un ataque de pánico en un avión. ¿Quién me da un cachetazo 'para que me calme'?",
  "Me postulo para Presidente. ¿Quién saca a la luz mis trapos sucios en la tele?",
  "Estoy borracho y quiero llamar a mi ex. ¿Quién es el que me da el teléfono en vez de sacármelo?",
  "Me caí en la calle y se me vieron hasta las ideas. ¿Quién se ríe antes de ayudarme?",
  "Tengo que esconder un cadáver en el baúl. ¿A quién llamo para que maneje el auto?",
  "Escribí un libro sobre mi vida. ¿Quién es el único que lo compra solo para criticarlo?",
  "Tengo que desactivar una bomba cortando el cable rojo o azul. ¿A quién NO dejo que decida?",
  "Estoy en un juicio por asesinato. ¿Quién es mi abogado que llega tarde y borracho?",
  "Le presté mi computadora a alguien y me la devolvió llena de virus. ¿Quién fue?",
  "Me hice vegano. ¿Quién me mete carne en la comida sin avisarme 'para joder'?",
  "Estoy ciego temporalmente. ¿Quién me guía directo hacia una pared?",
  "Me secuestraron. Los secuestradores piden rescate. ¿Quién dice 'quédenselo, no vale tanto'?",

  // --- SITUACIONES HIPOTÉTICAS ---
  "Llega un apocalipsis zombie. ¿Quién muere primero?",
  "Somos todos estrellas de rock. ¿Quién muere de sobredosis primero?",
  "Estamos perdidos en la selva. ¿Quién se come al grupo?",
  "El barco se hunde y hay un solo salvavidas. ¿Quién empuja a los demás?",
  "Nos ofrecen mil dólares por cada cucharada de caca. ¿Quién se hace rico?",
  "Hay un tiroteo y necesitamos un héroe. ¿Quién se esconde en el baño?",
  "Somos astronautas. ¿A quién dejamos en Marte?",
  "Estamos en un reality de supervivencia. ¿A quién votamos primero?",
  "Armamos una banda. ¿A quién echamos después del primer ensayo?",
  "Entramos todos a un culto. ¿Quién termina siendo el líder?",
  "El gobierno nos elige para una misión suicida. ¿A quién mandamos?",
  "Hay que donar un órgano para salvar al grupo. ¿Quién dice que sí pero nunca aparece?",
  "Nos contratan de strippers. ¿Quién tendría más éxito?",
  "Fundamos una startup juntos. ¿Quién se roba la plata y desaparece?",
  "Nos toca hacer un trabajo en grupo. ¿Quién no hace nada?",
  "Si nos secuestran a todos, ¿quién colabora con los secuestradores para salvarse?",
  "¿Quién de nosotros viviría en una casa embrujada y no se mudaría nunca?",
  "¿Quién de nosotros adoptaría un animal exótico ilegal como mascota?",
  "¿Quién de nosotros se convertiría en influencer insoportable?",
  "¿Quién haría paracaidismo sin pensarlo dos veces?",

  // --- AFIRMACIONES DIRECTAS (Dedocracia) ---
  "A todos nos da miedo subirnos al auto cuando maneja...",
  "Si hay alguien que va a morir solo, es...",
  "Si hay alguien capaz de vender a su madre, es...",
  "El que seguro tiene un cadáver enterrado en el patio es...",
  "Todos sabemos quién termina en la cárcel primero...",
  "Si hay alguien que ya cagó en la ducha, es...",
  "Todos sabemos quién se mea en la pileta...",
  "Si hay alguien que besa mal, es...",
  "El que seguro ronca como tractor es...",
  "Todos sabemos quién miente sobre su altura...",
  "Acá hay uno que se cree más lindo de lo que es, y es...",
  "El que seguro llora con películas de Disney es...",
  "Todos sabemos quién ghostea a la gente...",
  "Si hay alguien que se tira pedos y culpa al perro, es...",
  "El que tiene el peor gusto en música es...",
  "¿Quién de nosotros olvida el cumpleaños de su pareja?",
  "¿Quién olvida pagar una cuenta importante y le cortan la luz?",

  // --- SECRETOS Y TABÚES ---
  "Uno de nosotros tuvo piojos de grande. ¿Quién?",
  "Alguien acá besó a un primo. ¿Quién fue?",
  "Uno de nosotros cree que la Tierra es plana. ¿Quién?",
  "Alguien de este grupo se hizo pis en la cama después de los 15. ¿Quién?",
  "Uno de nosotros robó algo de un supermercado. ¿Quién?",
  "Alguien acá googleó su propio nombre. ¿Quién?",
  "Uno de nosotros lloró viendo un video de un perrito. ¿Quién?",
  "Alguien de acá tiene un OnlyFans secreto. ¿Quién?",
  "Uno de nosotros se enamoró de un profesor. ¿Quién?",
  "Alguien acá duerme con un peluche todavía. ¿Quién?",
  "Uno de nosotros mandó nudes a la persona equivocada. ¿Quién?",
  "Alguien de este grupo comió del piso. ¿Quién?",
  "Uno de nosotros se sacó una selfie llorando. ¿Quién?",
  "Alguien acá stalkeó al ex más de 6 meses. ¿Quién?",
  "Uno de nosotros habla solo en voz alta. ¿Quién?",
  "¿A quién le daría menos culpa acostarse con la expareja de un amigo?",
  "En el historial porno de quién encontraríamos cosas más raras?",
  "Uno de nosotros tuvo gonorrea y sífilis. ¿Quién?",
  "Un amigo necesita sangre, ¿quién dijo que fue a donar, pero nunca fue?",
  "Uno de nosotros es una estrella porno conocido como 'Beso Negro 2'. ¿Quién es?",
  "¿Quién de nosotros secretamente le desea la muerte a los demás?",
  "Si fuéramos los apóstoles, ¿quién sería Judas?",
  "¿Quién usa la ropa interior dos días seguidos?",
  "¿Quién tiene hongos en los pies ahora mismo?",

  // --- DINERO POR DIGNIDAD ---
  "¿Quién se tragaría vómito de perro por 5.000 dólares?",
  "¿Quién lamería el piso del subte por 10.000 dólares?",
  "¿Quién publicaría su historial de búsqueda por 50.000 dólares?",
  "¿Quién se dejaría tatuar lo que el grupo elija por 20.000 dólares?",
  "¿Quién viviría un año sin bañarse por un millón de dólares?",
  "¿Quién besaría a su ex en frente de todos por 1.000 dólares?",
  "¿Quién se afeitaría las cejas por 500 dólares?",
  "¿Quién llamaría a su madre y le gritaría por 2.000 dólares?",
  "¿Quién se metería a un contenedor de basura por 3.000 dólares?",
  "¿Quién comería comida de gato por una semana por 15.000 dólares?",
  "Si encontrara una billetera con 500 dólares y DNI, ¿quién se queda la plata y tira el DNI?",
  "¿Quién se casaría solo por la plata esperando a que el viejo/a se muera?",

  // --- ROLES NEGATIVOS ---
  "¿A quién NO querría jamás como jefe?",
  "¿A quién NO le confiarían un secreto?",
  "¿Quién sería el peor padre/madre?",
  "¿A quién NO dejarías cuidar tu casa?",
  "¿Quién sería el peor presidente?",
  "¿Quién daría los peores consejos de amor?",
  "¿A quién NO le prestarías plata?",
  "¿Quién sería el peor médico?",
  "¿Quién arruinaría una primera cita?",
  "¿A quién NO invitarías a un funeral?",
  "Necesitamos a alguien para comandar a nuestras tropas. Por favor QUE NO SEA...",
  "¿Quién de nosotros es secretamente un supervillano?",

  // --- PREDICCIONES DE VIDA ---
  "¿Quién sigue soltero a los 50?",
  "¿Quién se casa tres veces?",
  "¿Quién termina viviendo con sus padres para siempre?",
  "¿Quién va a ser millonario?",
  "¿Quién termina en un reality show?",
  "¿Quién va a tener 5 hijos?",
  "¿Quién se muda a otro país y nunca más vuelve?",
  "¿Quién termina siendo famoso?",
  "¿Quién se hace un lifting antes de los 40?",
  "¿Quién escribe un libro sobre su vida?",
  "¿Quién se va a casar con alguien que todavía no nació?",
  "¿Quién se tatuaría el nombre de su pareja al mes de conocerse?",

  // --- POSITIVAS (Para equilibrar un poco... o no) ---
  "¿A quién llamarías en la peor crisis de tu vida?",
  "¿Quién te prestaría plata sin preguntar?",
  "¿Quién te defendería en una pelea?",
  "¿A quién le confiarías tu contraseña del banco?",
  "¿Quién sería el mejor padrino/madrina?",
  "¿Quién te ayudaría a esconder un cuerpo sin preguntar?",
  "¿Con quién te irías de viaje sin pensarlo?",
  "¿Quién te diría la verdad aunque duela?",
  "¿A quién elegirías para tu equipo en el fin del mundo?",
  "¿Quién es el más leal de todos los que están acá?"
];