export const questions = [
  // --- PRIMERA PERSONA (Culpando al resto) ---
  "Amanecí sin un riñón en una bañera con hielo. El que me lo sacó para venderlo es...",
  "Mi pareja me mete los cuernos. El tercero en discordia de esta mesa es...",
  "Estoy en cana a las 4 AM con una sola llamada. A la persona que NO llamo ni en pedo es a...",
  "Estoy en coma. El que me desenchufa para cargar su celular es...",
  "Me voy de vacaciones. Al que no le dejaría mi mascota ni aunque me pague es a...",
  "Gané el Quini 6. El que aparece de la nada a pedirme plata es...",
  "Puse un bar. El que se toma toda la mercadería y me lo funde en un mes es...",
  "Tengo un secreto inconfesable. El chusma que seguro ya lo sabe es...",
  "Mandé nudes al grupo equivocado. El que hace captura de pantalla rápido es...",
  "Saltamos en paracaídas. El que me empuja sin el paracaídas puesto es...",
  "La policía encontró cocaína en mi auto. El que me la plantó es...",
  "Me desperté con un tatuaje tribal en la cara. El que me convenció de hacérmelo es...",
  "Me colgué de un precipicio. El que me pisa los dedos en vez de ayudarme es...",
  "Viene un zombie. El que me pega un tiro en la pierna para poder escaparse él es...",
  "Me hackearon el celular. El primero en buscar mis fotos en bolas es...",
  "Caí en una estafa piramidal. El que me metió en el 'Telar de la Abundancia' es...",
  "Estamos en un interrogatorio. El que se quiebra a los 2 minutos y me delata es...",
  "Me morí. Al que le doy mi contraseña para que borre mi historial de internet es a...",
  "Hice una fiesta sorpresa. El idiota que se le escapa y la arruina es...",
  "Me fui a vivir a Europa. El que me ocupa la casa y cambia la cerradura es...",
  "Tengo un ataque de pánico. El que me pega un cachetazo 'para que me calme' es...",
  "Estoy en pedo y quiero llamar a mi ex. El que me da el teléfono para cagarse de risa es...",
  "Tengo que esconder un cadáver. El que maneja el auto de la huida es...",
  "Hay que cortar el cable rojo o el azul. Al que NO dejo decidir ni loco es a...",
  "Estoy en juicio por asesinato. Mi abogado que llega tarde y con resaca es...",
  "Le presté mi compu a uno de ustedes. El que me la devolvió llena de virus porno es...",
  "Me hice vegano. El que me mete carne en la empanada para cagarme es...",
  "Me secuestraron. El que le dice a los secuestradores 'quédenselo, no vale nada' es...",

  // --- HIPOTÉTICAS (Catástrofes y Caos) ---
  "Somos una banda de rock. El que muere de sobredosis primero es...",
  "Nos perdimos en los Andes. Al primero que nos comemos es a...",
  "El barco se hunde y hay un solo lugar. El que empuja a una vieja para salvarse es...",
  "Hay un tiroteo. El que usa a un compañero de escudo humano es...",
  "Nos anotamos en Gran Hermano. Al que echan la primera semana por insoportable es a...",
  "Entramos a una secta. El que termina lavándole los pies al líder es...",
  "El gobierno nos manda a la guerra. El que se dispara en el pie para no ir es...",
  "Hay que donar un riñón para salvar al grupo. El que se hace el boludo es...",
  "Nos contratan de strippers. El que se llena de plata es...",
  "Fundamos una empresa juntos. El que se chorea la plata de la caja es...",
  "Hacemos un trabajo práctico. El que no hace nada y aprueba igual es...",
  "El que viviría en una casa embrujada solo porque el alquiler es barato es...",
  "El que se haría Influencer y vendería estafas cripto a sus seguidores es...",

  // --- DEDOCRACIA (Ataque directo) ---
  "A todos nos da miedo subirnos al auto si maneja...",
  "Si hay alguien que va a morir solo y rodeado de gatos, es...",
  "Si hay alguien capaz de vender a su propia madre por un iPhone, es...",
  "Todos sabemos que el primero de nosotros en ir preso es...",
  "El que seguro cagó en la ducha y lo empujó con el pie es...",
  "Todos sabemos que el que se mea adentro de la pileta es...",
  "Si hay alguien acá que besa como el orto, es...",
  "El que seguro ronca como un tractor viejo es...",
  "El que miente con los centímetros (de altura o de otra cosa) es...",
  "El que seguro llora mirando el Rey León es...",
  "El que se tira pedos y mira al de al lado haciéndose el boludo es...",
  "El que escucha la música más horrible del mundo es...",
  "El que se olvida el cumpleaños de su novia/o siempre es...",
  "Al que le cortan la luz todos los meses por colgado es a...",

  // --- SECRETOS (Incomodidad total) ---
  "El que tiene una cuenta fake para putear gente o stalkear es...",
  "El que seguro tiene (o pagaría) un OnlyFans es...",
  "El que se enamoró de un profesor/a en la secundaria es...",
  "El que se sacó una selfie llorando para subirla a Instagram es...",
  "El que todavía stalkea al ex de hace 5 años es...",
  "Al que le daría menos culpa comerse a la ex de un amigo es a...",
  "El dueño del historial de búsqueda donde encontraríamos porno de enanos es...",
  "El que tuvo gonorrea, sífilis o ladillas y no dijo nada es...",
  "Un amigo necesita sangre. El que dice que fue a donar y se quedó durmiendo es...",
  "La estrella porno frustrada del grupo es...",
  "Si fuéramos los apóstoles, el que haría de Judas es...",
  "El que usa el mismo calzoncillo/bombacha dos días seguidos es...",
  "El que tiene hongos en los pies y no se los cura es...",

  // --- DINERO VS DIGNIDAD ---
  "El que se traga un vómito ajeno por 10.000 dólares es...",
  "El que lame el pasamanos del subte B por 20.000 dólares es...",
  "El que se tatúa 'AMO A MILEI' en la frente por 100.000 dólares es...",
  "El que estaría un año sin bañarse por 1 millón de dólares es...",
  "El que se chapa a su ex frente a su pareja actual por 1.000 dólares es...",
  "El que se afeita las cejas por 500 dólares es...",
  "El que comería comida de gato una semana por 15.000 dólares es...",
  "Encontrás una billetera con guita y DNI. El que se queda la guita y tira el DNI es...",
  "El que se casaría con un viejo/a de 90 años millonario esperando que se muera es...",

  // --- ROLES DE MIERDA ---
  "Al que JAMÁS le contaría un secreto es a...",
  "El que sería el padre/madre más irresponsable es...",
  "Al que NO le dejaría las llaves de mi casa ni loco es a...",
  "El que sería el peor Presidente de la Nación es...",
  "El que da los consejos de amor más tóxicos es...",
  "Al que NO le prestaría plata porque no te la devuelve más es a...",
  "El médico que te operaría la pierna equivocada es...",
  "El que arruinaría una primera cita hablando de su ex es...",
  "Al que NO invitás a un funeral porque se ríe es a...",
  "El que secretamente es un psicópata es...",

  // --- FUTUROLOGÍA BARATA ---
  "El que sigue soltero/a a los 50 y viviendo con los viejos es...",
  "El que se casa y se divorcia 3 veces antes de los 50 es...",
  "El que va a terminar en cana por un malentendido (o no tanto) es...",
  "El que va a tener 5 hijos de 3 padres distintos es...",
  "El que se muda a otro país y se olvida de nosotros es...",
  "El que se opera toda la cara y queda irreconocible es...",
  "El que escribe un libro de autoayuda que nadie lee es...",
  "El que se va a casar con alguien que todavía no nació es...",
  "El que se tatúa el nombre de la pareja a la semana de conocerse es...",

  // --- LO TURBIO (Final Fuerte) ---
  "El que tiene un hijo no reconocido o una familia paralela es...",
  "El psicópata que revisa el celular de su pareja mientras duerme es...",
  "El que volvería con su ex aunque le haya arruinado la vida es...",
  "El cornudo/a consciente más grande del grupo es...",
  "El que tiene la ropa interior agujereada o manchada ahora mismo es...",
  "El que nos vendería a todos por un puesto político es...",
  "El que sabe dónde pegar merca a las 4 de la mañana un martes es...",
  "El que se va a quedar solo para siempre porque es insoportable es..."
];